linagora/customers#48: Move assets to specific folder
linagora/esn-frontend-inbox pull request #478
Opened 2021-06-17 10:23 UTC by renaudboyer

2021-06-17 10:50 UTC, tanandy approved these changes

2021-06-17 12:18 UTC, alagane requested changes

2021-06-17 12:18 UTC, alagane commented on assets/index.pug
> +    script(src=base + "assets/socket.io.js")
`socket.io/` should also be removed from `webpack.commons.js` line 90

2021-06-18 08:41 UTC, alagane submitted a review, later dismissed

2021-06-18 09:08 UTC, tanandy approved these changes

2021-06-18 12:29 UTC, alagane approved these changes

2021-06-18 12:30 UTC, merged